<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxyJ4bV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxyJ4bV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxyJ4bV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxyJ4bV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVxyJ4bV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VxyJ4bV',
    'container.build_id' => 'fb1b63c0',
    'container.build_time' => 1575302209,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxyJ4bV');
