<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY3BF3v7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY3BF3v7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY3BF3v7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY3BF3v7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerY3BF3v7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Y3BF3v7',
    'container.build_id' => '617830d3',
    'container.build_time' => 1577974971,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY3BF3v7');
